# Generated by Django 3.1.12 on 2025-04-09 20:09

from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Empleado')
    Group.objects.get_or_create(name='Admin')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250409_1402'),
    ]


    operations = [
        migrations.RunPython(create_groups),
    ]