# Generated by Django 3.1.12 on 2025-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Employee', 'Employee'), ('Admin', 'Admin')], default='Viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
