services:
  envoy:
    image: envoyproxy/envoy:v1.23-latest
    container_name: envoy_proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro  
    ports:
      - "10000:10000"  
      - "9901:9901"    
    depends_on:
      - django_project1
      - django_project2
      - postgres_db
    networks:
      - my_network

  django_project1:
    container_name: adoption_center
    build: .
    ports:
      - "8000:8000"
    command: gunicorn adoption_center.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres_db  
    networks:
      - my_network

  django_project2:
    container_name: adoption_center2
    build: .
    ports:
      - "8001:8001"
    command: gunicorn adoption_center.wsgi:application --bind 0.0.0.0:8001
    depends_on:
      - postgres_db  
    networks:
      - my_network

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: gaby_admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_adoption_center
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432" 
    networks:
      - my_network

volumes:
  postgres_data: 

networks:
  my_network:
    driver: bridge
