# Generated by Django 3.1.12 on 2025-04-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20250411_1046'),
        ('pets', '0002_auto_20250411_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
