# Generated by Django 3.1.12 on 2025-04-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20250411_1046'),
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.mascota'),
        ),
    ]
